### ISSUE TITLE
Microsoft Game Store Version no longer compatible with the DQXIS-SDK v0.7.6.1

### ISSUE THREAD

**Issue by Vanuatufish** [emoose/DQXIS-SDK#30]
I get an error message when trying to inject the xinput1_3.dll, saying the current game version is incompatible.

**Comment by mike9k1** [comment]
@Demolinizer has confirmed it for us (MS Store has updated again). Will try sending the .exe @emoose's way after running UWPDumper.

**Comment by RTH-Retribution** [comment]
https://drive.google.com/file/d/1Bh6vu7rgCkN17hSFa-X0tHv9B0xNQVg8/view?usp=sharing

@emoose here we are my guy

**Comment by emoose** [comment]
@Demolinizer thanks for dumping it!

EXE timestamp is ~13 days after the last MS store version added in https://github.com/emoose/DQXIS-SDK/commit/8597671e0075ab96581347335b077b3691b68542

Wonder when this update was pushed, also do you know if there's any version number for it anywhere? The last version was apparently 1.0.6.0 but I don't actually see it mentioned in the EXE anywhere, does it mention anything in the MS store?

Getting IDA to analyze it now, hopefully most of the offsets might still match up with that version.

**Comment by emoose** [comment]
Just pushed 0.7.6.2 which should have support for it: https://github.com/emoose/DQXIS-SDK/releases/tag/0.7.6.2

Hopefully ported everything across properly (seems data addrs were mostly the same, but the code was shifted by around 0x50 bytes or so), would appreciate if @Vanuatufish & @Demolinizer could give it a try & check that it's working fine now!

btw, could you check inside your installed apps list to see if any version number is listed there? Tried checking with MS store on my side but doesn't seem to list it anywhere if you don't own it, I did find there was a last modified date of 17th Sept on the store page though, so maybe that's when this update was pushed.

**Comment by RTH-Retribution** [comment]
> Just pushed 0.7.6.2 which should have support for it: https://github.com/emoose/DQXIS-SDK/releases/tag/0.7.6.2
> 
> Hopefully ported everything across properly (seems data addrs were mostly the same, but the code was shifted by around 0x50 bytes or so), would appreciate if @Vanuatufish & @Demolinizer could give it a try & check that it's working fine now!
> 
> btw, could you check inside your installed apps list to see if any version number is listed there? Tried checking with MS store on my side but doesn't seem to list it anywhere if you don't own it, I did find there was a last modified date of 17th Sept on the store page though, so maybe that's when this update was pushed.

Yep seems to work great, debugconsole shows and everything is as normal

**Comment by emoose** [comment]
Sweet, guess we can close this issue then.

If anyone has any problems with the new UWP build feel free to comment here though (also if anyone can find out the version number for it that'd be helpful, so we can track the updates for it)
