### ISSUE TITLE
Input unbinding

### ISSUE THREAD

**Issue by emoose** [emoose/DQXIS-SDK#4]
ATM there's no way to unbind any of the DefaultInput.ini bindings, or any bindings created by the game EXE (eg. the key bindings generated from GameUserSettings.ini's KeyConfigNumber), we can add new bindings fine, but not clear them...

This makes some bindings cause a conflict, eg. you can't bind FirstPersonCamera to a key/button that would move the character since first-person camera doesn't follow you, so char would move beyond the camera.

Maybe the game EXE should be patched so that it can't generate bindings, with the default bindings it would generate moved into Input.ini, similarly DefaultInput.ini could be moved over & cleared.

This way the user has full control over the bindings in their Input.ini file, with no way for the game to cause any conflicts.
(hardest part is finding where in the EXE these binds are created, maybe UE4.18 build can help with that.)

If anyone has any other ideas it'd be nice to hear them too.

**Comment by emoose** [comment]
0.5 now lets us prevent the game from creating any bindings outside of the Input.ini/DefaultInput.ini, meaning that all bindings can easily be changed just by editing those files :)

I think there's still room for improvement here though... atm the included Input.ini has to include default binds for the game to work properly, and we also need to copy in a blank DefaultInput.ini to replace the one used by the game.

Repacking the DefaultInput.ini into a .pak file would be a nice start, I'm not sure if there's any public tools for creating DQXI paks though...

**Comment by mike9k1** [comment]
https://zenhax.com/download/file.php?id=9678&sid=e5a0b2ee940810b2d2f63bcf12ad2ee8 -- credit **spiritovod** (based on earlier research by **infogram** ;)

Usage: u4pak_dq11_v2.py pack pakchunk0-WindowsNoEditor_P_Your_Pack_Name_Here_v0.1.pak Game

(where "Game" folder contains Config\DefaultInput.ini)

**Comment by emoose** [comment]
Aha awesome, thanks for the link!

I'm thinking to save users from needing to copy a bunch of files around maybe DQXIS-SDK could just create the DefaultInput.ini / .pak itself, extract it from the DLL resources or something, we do run our DllMain before the game loads up so I think it should have the same effect as user copying it themselves.
Either that or maybe find some way to patch the game so it ignores the original DefaultInput.ini, hmm...

Would also like some way of warning users if they don't have any binds setup in Input.ini too, not sure if I can always rely on the save folder being in the same spot tho... (I noticed there was even a seperate japanese "ドラゴンクエスト XI S 体験版" folder too, ugh >.>), I'll try looking into the game some more and see if there's a way to grab the path from memory or something.

E: alright, 0.5.2 should now stop DefaultInput.ini being read, and also gives users the option to write out a default Input.ini :)
