### ISSUE TITLE
Rebindable Console Key

### ISSUE THREAD

**Issue by Mancomb-Seepgood** [emoose/DQXIS-SDK#8]
The only way to access the console on various non-US keyboard layouts is to switch your keyboard layout in the Windows settings. Since this is rather annoying, is there any way you could include a rebindable console key in the input.ini?

The original version of DQXIHook actually already let you rebind the console key, but that feature hasn't been ported to the S-version yet.

**Comment by emoose** [comment]
Hmm, never knew that part of DQXIHook actually worked (heard conflicting things about it), I'll try looking into it soon.

In the meantime you could maybe try adding to top of `Documents\My Games\DRAGON QUEST XI S\Input.ini`:
`[/Script/Engine.InputSettings]` (if the section doesn't exist)
`ConsoleKeys=P` (the key you want to use, no + in front)

~~It might need `BindFromInputIniOnly=true` in DQXIS-SDK.ini for it to work though~~ (edit: nope)
(also I remember seeing something about UE4 rebinding the console key itself when ConsoleKeys is only set to Tilde, DQXI sets it to Tilde + Atmark which stops the rebinding from happening though)

Let me know how it works for you, could maybe include the ConsoleKeys line in future Input.ini so others can know if it's customizable.

**Comment by Mancomb-Seepgood** [comment]
That actually did the trick - thank you :)
